---
db:
  dsn: postgresql://megacommerce@cockroachdb:26257/megacommerce?sslmode=disable

seeding:
  number_of_suppliers: 100
  number_of_customers: 10
  number_of_products_per_supplier: 30
  number_of_suppliers_have_products: 10
  number_of_customers_have_orders: 10
  number_of_orders_per_customer: 10

minio:
  amazon_s3_endpoint: "minio:9000"
  amazon_s3_bucket: "uploads"
  amazon_s3_access_key_id: "minioadmin"
  amazon_s3_secret_access_key: "minioadmin"
  max_upload_workers: 10
