---
db:
  dsn: postgresql://megacommerce@localhost:26257/megacommerce?sslmode=disable

seeding:
  number_of_suppliers: 100
  number_of_customers: 10
  number_of_products_per_supplier: 30
  number_of_suppliers_have_products: 10

minio:
  amazon_s3_endpoint: "localhost:9000"
  amazon_s3_bucket: "uploads"
  amazon_s3_access_key_id: "minioadmin"
  amazon_s3_secret_access_key: "minioadmin"
